### ISSUE TITLE
Authenticate with the generated token

### ISSUE THREAD

**Issue by jonatasfl** [sizeg/yii2-jwt#12]
I'm trying to authenticate in my API with the generated token (my first time with JWT), but i'm receiving an Unauthorized error:

```javascript
{
    "name": "Unauthorized",
    "message": "Your request was made with invalid credentials.",
    "code": 0,
    "status": 401,
    "type": "yii\\web\\UnauthorizedHttpException"
}
```

I did as follows:

**LoginController**

```php
class LoginController extends ActiveController
{
    public $modelClass = 'app\models\User';

    public function actionAuth()
    {
        Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;

        $username = Yii::$app->request->post('username');
        $pass = Yii::$app->request->post('password');

        $modelUser = User::findByUsername($username);

        if ($modelUser && $modelUser->validatePassword($pass)) {
            $token = (string) User::generateToken();

            return [
                'status' => true,
                'message' => 'Success',
                'token' => $token,
            ];
        }

        return [
            'status' => false,
            'message' => 'Wrong username or password'
        ];

    }

}
```

**User (model)** 

```php
public static function generateToken()
    {
        $signer = new Sha256();
        $token = \Yii::$app->jwt->getBuilder()->setIssuer('http://myurl') // Configures the issuer (iss claim)
            ->setAudience('http://myurl') // Configures the audience (aud claim)
            ->setId('myid', true) // Configures the id (jti claim), replicating as a header item
            ->setIssuedAt(time()) // Configures the time that the token was issue (iat claim)
            ->setNotBefore(time() + 60) // Configures the time before which the token cannot be accepted (nbf claim)
            ->setExpiration(time() + 3600) // Configures the expiration time of the token (exp claim)
            ->set('uid', 1) // Configures a new claim, called "uid"
            ->sign($signer, 'testing') // creates a signature using "testing" as key
            ->getToken(); // Retrieves the generated token

        return $token;
    }
```

**Rest Controller**

```php
public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['authenticator'] = [
            'class' => JwtHttpBearerAuth::className(),
        ];
        return $behaviors;
    }
```

Am I forgetting something to work properly?
Thank you!

**Comment by jonatasfl** [comment]
@sizeg I'm sending the header Authorization: Bearer MY_TOKEN
![capturar](https://user-images.githubusercontent.com/3798405/41192346-9a0d2416-6bd2-11e8-93f0-67f646682ab7.PNG)

Thank you!

**Comment by jonatasfl** [comment]
I found a solution...

In my Controllers I need to change the authenticator behavior from `JwtHttpBearerAuth::className()` to `HttpBearerAuth::className()` (Yii2 native)

In User Model I need to implement the **findIdentityByAccessToken** method as follow:
```php
public static function findIdentityByAccessToken($token, $type = null)
    {
        $token = \Yii::$app->jwt->getParser()->parse((string) $token); // Parses from a string
        $signer = new Sha256();

        $data = \Yii::$app->jwt->getValidationData(); // It will use the current time to validate (iat, nbf and exp)
        $data->setIssuer('http://myurl');
        $data->setAudience('http://myurl');
        $data->setId('myid');

        $username = $data->getClaim('username');

        if ($token->validate($data) && $token->verify($signer, 'testing')) {
            return static::findByUsername($username);
        }

        return null;
    }
```

**Comment by bologer** [comment]
@sizeg btw, why did `JwtHttpBearerAuth::className()` not work ? This is strange. I am also having the same issue. Placing break point at init() of `JwtHttpBearerAuth::className()` and get nothing. `HttpBearerAuth::className()` seems to be ok. 

```php
public function behaviors()
{
    $behaviors = parent::behaviors();
    $behaviors['authenticator'] = [
        'class' => JwtHttpBearerAuth::class,
    ];
    return $behaviors;
}
```

Could you briefly explain the work flow? Or maybe provide some example in the README.

__My case:__ 
I have React app and I would like to use Yii2 as backend. 

__I assume the flow should be following:__
I should have LoginController to have authentication endpoint to generate and save JWT for user. On success I place cookie on user side and every further request should be adding authentication header with the JWT token. 

Is it correct?

**Comment by sizeg** [comment]
@bologer 
1. You authenticate client with it credentials as usual.
2. After u validate his credentials you may generate JWT and send back it with response to client and store it
3. Then you may authenticate with JWT. You should send it in request header `Authorization`.

I've just check and provide u example some examples

1. Create application for example basic
`composer create-project --prefer-dist --stability=dev yiisoft/yii2-app-basic yii2-jwt-test`
2. Install jwt component
`composer require sizeg/yii2-jwt`
3. Add to config/web.php into `components` section
```php
$config = [
    'components' => [
        // other default components here..
        'jwt' => [
            'class' => 'sizeg\jwt\Jwt',
            'key'   => 'secret',
        ],
    ],
];
```
4. Change method `app\models\User::findIdentityByAccessToken()`
```php
    /**
     * {@inheritdoc}
     * @param \Lcobucci\JWT\Token $token
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        foreach (self::$users as $user) {
            if ($user['id'] === (string) $token->getClaim('uid')) {
                return new static($user);
            }
        }

        return null;
    }
```
5. Create controller for test
```php
<?php

namespace app\controllers;

use sizeg\jwt\Jwt;
use sizeg\jwt\JwtHttpBearerAuth;
use Yii;
use yii\rest\Controller;

class RestController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['authenticator'] = [
            'class' => JwtHttpBearerAuth::class,
            'optional' => [
                'login',
            ],
        ];

        return $behaviors;
    }

    /**
     * @return \yii\web\Response
     */
    public function actionLogin()
    {
        // here you can put some credentials validation logic
        // so if it success we return token
        $signer = new \Lcobucci\JWT\Signer\Hmac\Sha256();
        /** @var Jwt $jwt */
        $jwt = Yii::$app->jwt;
        $token = $jwt->getBuilder()
            ->setIssuer('http://example.com')// Configures the issuer (iss claim)
            ->setAudience('http://example.org')// Configures the audience (aud claim)
            ->setId('4f1g23a12aa', true)// Configures the id (jti claim), replicating as a header item
            ->setIssuedAt(time())// Configures the time that the token was issue (iat claim)
            ->setExpiration(time() + 3600)// Configures the expiration time of the token (exp claim)
            ->set('uid', 100)// Configures a new claim, called "uid"
            ->sign($signer, $jwt->key)// creates a signature using [[Jwt::$key]]
            ->getToken(); // Retrieves the generated token

        return $this->asJson([
            'token' => (string)$token,
        ]);
    }

    /**
     * @return \yii\web\Response
     */
    public function actionData()
    {
        return $this->asJson([
            'success' => true,
        ]);
    }
}
```
6. Send simple login request to get token. Here we does not send any credentials to simplify example. As we specify in `authenticator` behavior action `login` as optional the `authenticator` skip auth check for that action.
![image](https://user-images.githubusercontent.com/4047591/54614758-c4d2e100-4a7e-11e9-9175-0f1742bf4047.png)
7. First of all we try to send request to rest/data without token and getting error `Unauthorized`
![image](https://user-images.githubusercontent.com/4047591/54615287-a3262980-4a7f-11e9-81a9-609f5cb443c7.png)
8. Then we retry request but already adding `Authorization` header with our token
![image](https://user-images.githubusercontent.com/4047591/54615245-8ee22c80-4a7f-11e9-9948-e3f801596c43.png)

**Comment by bologer** [comment]
@sizeg wow, thank you for in-depth explanation!

What do you think about putting this in the WIKI? I think it could be useful to many people who cross similar issue as me. Also I crossed this article after you replied which explains it nicely as well.

**Comment by sizeg** [comment]
@bologer I've just update readme. You are welcome 👍

**Comment by ebinmanuval** [comment]
I am geting an exception **Access to undeclared static property: api\\models\\User::$users**

![image](https://user-images.githubusercontent.com/7802869/61181618-055ff700-a63a-11e9-879a-f1eacab63abf.png)

**Comment by bologer** [comment]
@ebinmanuval it seems you are using basic template and you probably deleted static property on `User` model. It is a mock array of users used to authenticate users. You should change all of the methods which depend on `$users` static property ot database ActiveRecord or just revert static propert back.

**Comment by racielbd** [comment]
Hi i know this issue is clouse but i still got an problem.., and i think you can help me here is the issue link #23 
Thanks in advance...

**Comment by Den2016** [comment]
> @ebinmanuval it seems you are using basic template and you probably deleted static property on `User` model. It is a mock array of users used to authenticate users. You should change all of the methods which depend on `$users` static property ot database ActiveRecord or just revert static propert back.

Ну у меня на свежем advanced то же самое получилось. Переделал на более простой вариант


    public static function findIdentityByAccessToken($token, $type = null)
    {
        return self::findIdentity($token->getClaim('uid'));
    }

findIdentity лежит прям рядом, ищет пользователя по id, возвращает то, что надо ))
Использую Apache 2.4, PHP 7.2
