### ISSUE TITLE
confused by "verify" function

### ISSUE THREAD

**Issue by medmin** [sizeg/yii2-jwt#15]
Hi, sizeg,

I am confused by the `verify` function.

```php
var_dump($token->verify($signer, $keychain->getPublicKey('file://{path to your public key}'))); // true when the public key was generated by the private one =)
```

So, the `verify` function belongs to the `$token` variable, which is an `object`, not a `string`. 

How do I verify a token `string` if a client app ( such as a web app built with React or Vuejs )  sends a token string back in the http header ?

I hope this is not a stupid question. Thanks.

**Comment by ngoctai** [comment]
`$token = Yii::$app->jwt->getBuilder()->getToken()` return a **Lcobucci\JWT\Token** object but it has explicit convert function to string.
So what will response to client script (vue) is `(string) $token` instead of `$token`. Client script is only working with string token

**Comment by sizeg** [comment]
May be also this https://github.com/sizeg/yii2-jwt#parsing-from-strings can helps?

**Comment by medmin** [comment]
Thanks. I have figured it work.

The `Parser` can convert a token `string` to a token `object` and then, we can use `$token->verify()` function.
