### ISSUE TITLE
How to logout?

### ISSUE THREAD

**Issue by im-zhangxi** [sizeg/yii2-jwt#18]

**Comment by im-zhangxi** [comment]
Help me !

**Comment by sizeg** [comment]
@im-zhangxi nice question. Hope this article helps you https://medium.com/devgorilla/how-to-log-out-when-using-jwt-a8c7823e8a6

**Comment by im-zhangxi** [comment]
> @im-zhangxi nice question. It demands on your needs and realization and has no ready answer. Hope this article helps you https://medium.com/devgorilla/how-to-log-out-when-using-jwt-a8c7823e8a6

thanks.
