### ISSUE TITLE
Not Found (#404)

### ISSUE THREAD

**Issue by edgarleite** [sizeg/yii2-jwt#20]
When I try to access login or data methods, a 404 error is displayed. To fix, use this setting on config file: 

`                [
                    'class' => 'yii\rest\UrlRule',
                    'controller' => 'rest', 
                    'extraPatterns' => [
                        'GET login' => 'login',
                        'GET data' => 'data',
                    ], 
                ], 
`

**Comment by sizeg** [comment]
If you are about example from readme, then I'm using basic app out of box without any other modifications to url rules. By default `urlManager` component is commented in web.php config file. Seems you have extra setup for this.
