### ISSUE TITLE
lcobucci/jwt version constraint

### ISSUE THREAD

**Issue by Stevad** [sizeg/yii2-jwt#22]
Hi. 

In `composer.json` I see that dependency is set to `"lcobucci/jwt": "~3.2.0",`. But now that package is already has 3.3.x version.

Are you going to update version constraint? JWT is kind of feature that is better to keep up to date.

**Comment by sizeg** [comment]
@Stevad, Hi!

This is a migration version between 3 and 4 major releases. I'm not decide is to wait for 4.x or make supp for 3.3.x. There are no significant changes yet.
