### ISSUE TITLE
Options method not allowed

### ISSUE THREAD

**Issue by racielbd** [sizeg/yii2-jwt#23]
Hi
I am trying to use the jwt in yii with vue as a front-end framework but the browser before executing the post excecute an options request and gives me unauthorized action. looking for a solution i found one but it doesn't work as expected.
the solution that i found
1. created a customCors
```
class CustomCors extends Cors
{
    public function beforeAction($action)
    {
        parent::beforeAction($action);
        if (Yii::$app->getRequest()->getMethod() === 'OPTIONS') {
            Yii::$app->getResponse()->getHeaders()->set('Allow', 'POST GET PUT');
            Yii::$app->end();
        }
        return true;
    }
}
```

2. On the behaviors of the controllers 
```
public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['contentNegotiator'] = [
            'class' => ContentNegotiator::className(),
            'formats' => [
                'application/json' => Response::FORMAT_JSON,
            ],
        ];
        // add CORS filter for browers with Option on query distants domains
        $behaviors['corsFilter'] = [
            'class' => CustomCors::className(),
        ];
        $behaviors['authenticator'] = [
            'class' => JwtHttpBearerAuth::class,
            'except' => [
                'authenticate',
                'options',
            ],
        ];
        return $behaviors;
    }
```
3. this the cofig in case you have to make any changes in it...
```
'urlManager' => [
            'enablePrettyUrl' => true,
            'enableStrictParsing' => false,
            'showScriptName' => false,
            'rules' => [
                [
                    'class' => 'yii\rest\UrlRule',
                    'pluralize' => false,
                    'controller' => [
                        'user'
                    ],
                    'tokens' => [
                        '{action}' => '<action:[a-zA-Z0-9\\-]+>',
                    ],
                    'extraPatterns' => [
                        'OPTIONS {action}' => 'options',
                        'POST authenticate' => 'authenticate',
                        'POST signup' => 'signup',
                    ],
                ]
            ],
        ],
```
the token its ok because in the postman app works ok, but in the mozilla firefox no matter wath I still receive unauthorized access
I would appreciate any help
Thanks in advance...

**Comment by ebinmanuval** [comment]
public function behaviors()
    {
   
        
        $behaviours = parent::behaviors();


        
        if (Yii::$app->request->method!='OPTIONS') {
            $behaviours['authenticator'] = [
                'class' => \sizeg\jwt\JwtHttpBearerAuth::class,
            ];
        }
return $behaviours;
    }

**Comment by racielbd** [comment]
> 
> 
> public function behaviors()
> {
> 
> ```
>     $behaviours = parent::behaviors();
> 
> 
>     
>     if (Yii::$app->request->method!='OPTIONS') {
>         $behaviours['authenticator'] = [
>             'class' => \sizeg\jwt\JwtHttpBearerAuth::class,
>         ];
>     }
> ```
> 
> return $behaviours;
> }

I tried that solution and it didn't work but it gave me the idea of how to find a solution to the problem... thanks for the quick response....
the controller have to be like these to work 
Solution: Controller behavior

```
public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['contentNegotiator'] = [
            'class' => ContentNegotiator::className(),
            'formats' => [
                'application/json' => Response::FORMAT_JSON,
            ],
        ];
        $auth = $behaviors['authenticator'];
        unset($behaviors['authenticator']);
        // add CORS filter para los navegadores con Option al consultar dominios distantes
        $behaviors['corsFilter'] = [
            'class' => CustomCors::className(),
        ];
        $behaviors['authenticator'] = $auth;

        $behaviors['authenticator'] = [
            'class' => JwtHttpBearerAuth::class,
            'except' => [
                'authenticate',
                'options',
            ],
        ];
        return $behaviors;
    }
```

**Comment by astwinioenergy** [comment]
>         $behaviors['authenticator'] = [
>             'class' => JwtHttpBearerAuth::class,
>             'except' => [
>                 'authenticate',
>                 'options',
>             ],

What does "options" action do?
