### ISSUE TITLE
Changelog File

### ISSUE THREAD

**Issue by nadar** [sizeg/yii2-jwt#24]
Hi, we are thinking about to implement this library as an option for auth mechanism by default for LUYA => https://github.com/luyadev/luya

In order to have a more readability i would suggest to have a changelog file and also write down on what type of versioning you plan to release the library (for example semver i assume). This would be good for us to have more transparency.

Thanks for making such a good library, if we have inputs you can be sure to get some PRs :-)

**Comment by sizeg** [comment]
@nadar, thank you for your interest. At that moment I have no plans to keep a changelog. The version semantic is the same to Yii.

**Comment by nadar** [comment]
I would suggest to make write down those informations, because yii2 versioning strategy requires `~1.0.0` instead of `^1.0` which is composer default. So the installation description in the readme `composer require sizeg/yii2-jwt` would be wrong.

**Comment by sizeg** [comment]
Caret ^1.0 is equivalent to >=1.0.0 <2.0.0 and has no break backwards compatibility until 2.0 will release. Have no any problems with it.
