### ISSUE TITLE
JwtHttpBearerAuth not checking iss/aud

### ISSUE THREAD

**Issue by eborned** [sizeg/yii2-jwt#25]
At the moment, the JwtHttpBearerAuth only checks for expiration.  Best practice is to check both on the recieving end:

> The consumer of a JWT should always check that the "iss" claim matches the expected issuer (e.g., sso.example.com).

> The consumer of a JWT should always verify that the audience matches its own identifier. The value of this claim is again a string value, at the discretion of the issuer. In OAuth 2.0 and OpenID Connect scenarios, this value typically contains the client identifier (e.g., api.example.com).

At the moment, the only way to validate those parameters, is to check the token claims when locating the user in the database. This is ok, but I think most people will forget to check this because it's not in the examples. Maybe you should include an option in the `JwtHttpBearerAuth` to add additional claim validation (I noticed a TODO there). Or extend the examples with aud/iss checks in the `findIdentityByAccessToken` method?

**Comment by sizeg** [comment]
@eborned thanks for applying. `JwtHttpBearerAuth` does not check any token data and should not. By default this filter just pass JWT to the `loginByAccessToken()` method of the `user` application component.

Before token pass to the `loginByAccessToken()`, this filter trying to get `Token` class from `jwt` application component, in which token validation occurs https://github.com/sizeg/yii2-jwt/blob/v1.2.0/Jwt.php#L93
To add any checks extends `Jwt` class and override the `validateToken()` method https://github.com/sizeg/yii2-jwt/blob/v1.2.0/Jwt.php#L111

**Comment by sizeg** [comment]
@eborned I've added JwtValidationData class with a new release and provide usage example. Hope you will enjoy it.
