### ISSUE TITLE
Problem with Claim uid

### ISSUE THREAD

**Issue by ammasum** [sizeg/yii2-jwt#28]
When i use Manually `->withClaim('uid', 100)` it's working  fine.
if i change uid to 120 or others number `->withClaim('uid', 120)` it's show me "message": "Your request was made with invalid credentials.". But if add others Claim like `->withClaim('name', "Any name")` . it's also work. Why it's problem with changing uid.
Note: My code is exactly README.md Yii2 basic template example.

**Comment by sizeg** [comment]
Hi, so if u just change the only `->withClaim('uid', 120)` then you should have such user id or no. https://github.com/yiisoft/yii2-app-basic/blob/2.0.26/models/User.php#L14
