### ISSUE TITLE
Optional login action

### ISSUE THREAD

**Issue by tomislav13** [sizeg/yii2-jwt#29]
Regards,
'optional' parameter for login action is not working,
the request "GET /login" returns this: 
```
{
  "name": "Unauthorized",
  "message": "Your request was made with invalid credentials.",
  "code": 0,
  "status": 401,
  "type": "yii\\web\\UnauthorizedHttpException"
}
```
I have tried with except like this:
```
 $behaviors = parent::behaviors();
        $behaviors['authenticator'] = [
            'class' => JwtHttpBearerAuth::class,
            'except' => ['login'],
            'optional' => [
                'login',
            ]
        ];
```
but it doesn't work either.
Also, what is self::$users in User model (and the strange foreach loop :) )? My IDE reports it as undefined...

**Comment by ronashdkl** [comment]
i fixed it by replacing  findIdentityByAccessToken as below. 

    public static function findIdentityByAccessToken($token, $type = null)
    {
       return  self::findOne(['id'=>(string) $token->getClaim('uid')]);

    }

**Comment by tomislav13** [comment]
Thanks Ronash!

My original problem was because of requesting wrong url :) Nevermind.
But just for info, this is how method you mentioned looks in my code:
```
public static function findIdentityByAccessToken($token, $type = null)
{
    return self::findIdentity($token->getClaim('uid'));
}
```
It may be better because this findIdentity($id) method checks for user's status
(for example, if user is not active - he should not be permitted to log in)

Best regards

**Comment by sizeg** [comment]
Hi,

> Also, what is self::$users in User model (and the strange foreach loop :) )? My IDE reports it as undefined...

As u can see example from documentation is about Yii2 basic template https://github.com/yiisoft/yii2-app-basic/blob/2.0.32/models/User.php#L13
