### ISSUE TITLE
have cors origin problem when use authenticator

### ISSUE THREAD

**Issue by mamadza** [sizeg/yii2-jwt#30]
Hi, I have problem 
I know It's not the issue of this package but I'm confusing about this cors errors

I have CustomController extend from yii\rest\controller

`    
    
    public function behaviors()
    {
        $behaviors = parent::behaviors();
         $auth = $behaviors['authenticator'];
        unset($behaviors['authenticator']);

        $behaviors['corsFilter'] = [
            'class' => Cors::className(),
            'cors'  => [
                'Origin'                           => ['*'],
                'Access-Control-Request-Method'    => ['POST', 'GET', 'OPTIONS'],
                'Access-Control-Allow-Headers' =>  ['*'],
                'Access-Control-Expose-Headers' => ['*']
            ],
        ];

        $behaviors['authenticator'] = $auth;
        $behaviors['authenticator']['except'] = ['options'];

        return $behaviors;
    }`

when I want to use authentication in special controller
and when use 

`    

    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['authenticator'] = [
            'class' => JwtHttpBearerAuth::class,
            'optional' => [
                'login',
            ],
        ];

        return $behaviors;
    }

`

I get this error:
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost/shop/api/v1/checkout/addresses. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

when I check the header, the header of origin are remove from request 
I don't have problem in another controller

**Comment by mamadza** [comment]
This issue is not about this package , my wrapper class for axios remove header and I found the problem

**Comment by mamadza** [comment]
I have problem with this, I install bizly package forked from this package and I dont have problem with that package

**Comment by sizeg** [comment]
Have you added options action?

```php
   /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'options' => [
                'class' => 'yii\rest\OptionsAction',
            ],
        ];
    }
```
