### ISSUE TITLE
This token library can't invalidate or force to expire

### ISSUE THREAD

**Issue by williamgomez71** [sizeg/yii2-jwt#32]
Hi,

I am try to remove the token  or force to expire when the users logout, but I cant archive this. 

I try to setup time expiration time but not work.

 $time = time();
        Yii::$app->jwt->getParser()->parse((string) $token)->expiresAt($time+1);
        Yii::$app->jwt->loadToken(Yii::$app->jwt->getParser()->parse((string) $token))->expiresAt($time+1);

Other use case is when I want to grow up the expiration time, because the user manting the app open.

I thing that is a bug or issue.

**Comment by AnatolyRugalev** [comment]
Hi.

What you're trying to achieve is token revocation. JWT tokens cannot be modified after issuing them to the user. However, you can implement revocation mechanics by keeping revoked token IDs in some sort of cache.

Extending token expiration could be achieved in a similar way, but I wouldn't recommend it - you probably should use refresh token for this purpose.

**Comment by sizeg** [comment]
lcobucci/jwt#251 (comment)

P.S. U may search for other questions by "refresh" keyword to find answers.
