### ISSUE TITLE
How to increase the JWT Token Expiry Time?

### ISSUE THREAD

**Issue by manikandan-raman** [sizeg/yii2-jwt#33]
Initially, I have set 15 minutes for the expiration. Even though if a user stays active, after 15 minutes it returning 401 invalid token error. Is there any way to increase the expiry time at each request, so that it won't throw the error if the user stays active.

**Comment by sizeg** [comment]
@Maniyuvan shortly, no

lcobucci/jwt#251 (comment)

P.S. U may search for other questions by "refresh" keyword to find answers.
