### ISSUE TITLE
Support of lcobucci/jwt 3.4

### ISSUE THREAD

**Issue by xfuturomax** [sizeg/yii2-jwt#34]
Some libs require new version of lcobucci/jwt, for example kreait/firebase-php. Is it possible to add support for new version?

**Comment by sizeg** [comment]
Hi, I'll add it soon. It's need some work on it.

**Comment by karensg** [comment]
Would be awesome with PHP 8.0 available. 
lcobucci/jwt 3.3 only supports ^7.0

**Comment by bizley** [comment]
My fork takes care of it for some time already https://github.com/bizley/yii2-jwt

**Comment by sizeg** [comment]
#41

3.4 will not sup for now, only 4.2.x and higher
