### ISSUE TITLE
Support PHP 8

### ISSUE THREAD

**Issue by zantdev** [sizeg/yii2-jwt#36]

**Comment by winternet-studio** [comment]
It is important to have this soon. We have a site in production that is dependent on this package, and currently we can't use PHP 8 because it is using lcobucci/jwt less than version 4.0.0.

**Comment by nadar** [comment]
*BUMP* :-)

**Comment by nadar** [comment]
@sizeg is your library maintained anymore?

**Comment by bizley** [comment]
@nadar please take a look at https://github.com/bizley/yii2-jwt

**Comment by sizeg** [comment]
#41
