### ISSUE TITLE
Upgrade lcobucci/jwt package to 4.X

### ISSUE THREAD

**Issue by markch123** [sizeg/yii2-jwt#43]
Hi,

Tried installing yii2-jwt via composer and hit this

`- lcobucci/jwt[3.3.0, ..., 3.3.3] require php ^5.6 || ^7.0 -> your php version (8.1.10) does not satisfy that requirement.
`
Is it possible to update to 4.x which supports php 7.4/8?

Regards
Mark

**Comment by sizeg** [comment]
Hello, @markch123 

You can use on your own the beta supporting PHP 7.4 and 8.

https://github.com/sizeg/yii2-jwt/tree/v4.0-beta 

It will be released soon

**Comment by markch123** [comment]
cheers.
