### ISSUE TITLE
How to authorize from yii2?

### ISSUE THREAD

**Issue by dakipro** [sizeg/yii2-jwt#5]
Hi,
I started using this extension, and being new to yii2 it took me some time to figure things out.

After login I generate Hmac signed token like in examples here, and then I send it to the client.
I then on each request send that token as a Authentication - Bearer header, and i see that yii2 calls the validateToken funciton with all the data from the token. However, it always return false for authorization (401: Your request was made with invalid credentials).

Do I need to manually verify token on each request, or will Yii2 do that automatically?

Do I need to set up these manually again $data->setIssuer('http://mydomain.com'); $data->setAudience('http://mydomain.com'); $data->setId('4f1g23a12aa'); ?

If so, do you have any suggestions how/where do I add the code?
Thanks

**Comment by sizeg** [comment]
Hi,
sorry for the late answer.

Try to extend method [[sizeg\jwt\Jwt::validateToken()]] and add you claims. This is in plans to automate it setup. You can find what exactly you should add to validating here https://github.com/sizeg/yii2-jwt#validating.
