### ISSUE TITLE
$authHeader = $request->getHeaders()->get('Authorization');

### ISSUE THREAD

**Issue by mivans** [sizeg/yii2-jwt#7]
Unable to get authorization value

**Comment by AnatolyRugalev** [comment]
@mivans, could you please provide more details about the issue? As I can see now, it's not related to this package

**Comment by mivans** [comment]
Request header set X-Authorization can be received, but the default Authorization can not receive the token, return NULL

**Comment by mivans** [comment]
<img width="1366" alt="1" src="https://cloud.githubusercontent.com/assets/4272244/25330523/81ae9ffc-2912-11e7-8f32-cd3f9193405f.png">
<img width="1345" alt="2" src="https://cloud.githubusercontent.com/assets/4272244/25330524/81af30e8-2912-11e7-856b-418f52a58f71.png">

**Comment by AnatolyRugalev** [comment]
Is your application configured properly? Can you post here controller's behaviors configuration?

**Comment by mivans** [comment]
public function behaviors()
    {
        return [
            'contentNegotiator' => [
                'class' => ContentNegotiator::className(),
                'formats' => [
                    'application/json' => Response::FORMAT_JSON,
                ]
            ],
            'authenticator' => [
                'class' => JwtHttpBearerAuth::className()
            ]
        ];
    }

**Comment by mivans** [comment]
I just changed to X-Authorization is normal, Authorization returns null

**Comment by AnatolyRugalev** [comment]
You did not configure `AccessControl` behavior for your controller.

When you're requesting controller with `Authorization` header JwtBearerAuth cannot authorize request (wrong token?) and fails with 401 code. Any requests with a different header or without any header are succeeded because no access control configured. This controller can be accessed as a guest.

**Comment by mivans** [comment]
Apache into nginx can receive authorization, it should be apache settings

**Comment by Den2016** [comment]
Соори за русский))) В инглише не силен ))
Словил такую же беду - заголовок режется и не доходит до проверки. Наверное стоит сделать возможность конфигурирования кастомных заголовков, чтобы вместо Autorization можно было отправлять-проверять что-нибудь вроде Auth-Token

**Comment by Den2016** [comment]
Итак, покопавшись пару часов и поэкспериментировав пришел к выводу, что существуют условия, при которых заголовок Authorization не доходит до скрипта. Для воспроизведения этого необходим Apache 2.4 и php-fpm, который работает через proxy_fcgi. Подробности [здесь](https://httpd.apache.org/docs/2.4/en/mod/core.html#cgipassauth). В качестве объезда предлагается принудительно включить CGIPassAuth, но на моем сервере эта директива не работает. В конфигурации Apache & mod_php этой проблемы нет, но эта конфигурация в моем случае дает только php5.6, хотелось переходить на php7 как можно более плавно, но параллельно семерку могу запустить только через php-fpm.
Придется делать наследника от JwtHttpBearerAuth и переопределять метод authenticate, раз не предусмотрена кастомизация названия заголовка и схемы
