### ISSUE TITLE
Token is empty

### ISSUE THREAD

**Issue by pptyasar** [sizeg/yii2-jwt#8]
`$token->getClaims() `and other functions are returning value but `$token` is empty

**Comment by jpayne-cxp** [comment]
You need to either `echo $token`, or use `$token->getPayload()` to get the actual token. I struggled wit that for a bit too. @pptyasar

**Comment by HiepNinh** [comment]
Can you tell me how to get full token. getPayload() just return header and payload but I want to return signature too. Thanks.

**Comment by sizeg** [comment]
@HiepNinh, the string representation of the token object:
```php
echo $token;
// or
$stringToken = (string) $token;
```

**Comment by sizeg** [comment]
@HiepNinh full token `echo $token;` or `$var = (string) $token;`

**Comment by HiepNinh** [comment]
It didn't work for me.
Here is my code
$signer = new Sha256();
            //Generate token
            $token = Yii::$app->jwt->getBuilder()->setIssuer(Yii::$app->params['issuer'])
            ->setId(Yii::$app->params['token_id'], true)
            ->setIssuedAt(time())
            ->setExpiration(time() + Yii::$app->params['expired_time'])
            ->set('username', $params['username'])
            ->set('password', $params['password'])
            ->getToken(); // Retrieves the generated token

            return (string)$token;
 I'm using postman to post API and I just receive
"eyJ0eXAiOiJKV1QiLCJhbGciOiJub25lIiwianRpIjoiaXF1YWhDYWg3YXUifQ.eyJpc3MiOiJhcGkuY2h1eWVudGllbm5oYW5oMjRoLmxvY2FsIiwianRpIjoiaXF1YWhDYWg3YXUiLCJpYXQiOjE1MjIxNDgxOTMsImV4cCI6MTUyMjE1MTc5MywidXNlcm5hbWUiOiJhZG1pbiAiLCJwYXNzd29yZCI6IjEyMzQ1NiJ9."

**Comment by HiepNinh** [comment]
Oop!!, my fault, I forgot sign(). It work properly. Thank @sizeg
